### PR TITLE
feat: replace all option to replace all occurrences

### PR DESCRIPTION
**Pull request by amphetamarina**
adds a replaceAll: (true/false) option to replace all occurrences

### CODE REVIEW

**Review by kishyr — APPROVED** [review]

**Comment by JDBeaulieu-ProductMadness** [comment]
Any chance of merging this soon? I would be happy to use the replaceAll parameter!

**Review by kishyr — APPROVED** [review]

**Comment by JDBeaulieu-ProductMadness** [comment]
Hi @kishyr  is it possible to make a release of now that the changes have been merged?

**Comment by kishyr** [comment]
@JDBeaulieu-ProductMadness Done: https://github.com/mad9000/actions-find-and-replace-string/releases/tag/3

**Comment by JDBeaulieu-ProductMadness** [comment]
Thanks a lot! Much appreciated

**Pull request merged**
